services:
  app:
    build: .
    container_name: app
    restart: always
    command: npm run dev
    ports:
      - 8000:8000
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: db
    restart: always
    shm_size: 128mb
    user: 1000:1000
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 10
