name: Deploy frontend

on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  VITE_APP_URL: ${{ vars.VITE_APP_URL }}
  VITE_API_URL: ${{ vars.VITE_API_URL }}
  VITE_MAPS_ENABLED: ${{ vars.VITE_MAPS_ENABLED }}
  VITE_YMAPS_API_KEY: ${{ vars.VITE_YMAPS_API_KEY }}

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file
        run: env | grep -E 'VITE_' > ./frontend/.env
      - name: Build image
        run: docker build ./frontend -t ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest
      - name: Push image to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest

  pull-and-run:
    runs-on: ubuntu-24.04
    environment: production
    needs: build-and-publish
    steps:
      - name: Pull and run image on EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop charity-app-frontend || true
            docker rm charity-app-frontend || true
            docker pull ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest
            docker run -d -p 8001:80 --name charity-app-frontend ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest
          EOF
