name: Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build images
        run: |
          rm ./frontend/.env
          docker build ./backend -t ${{ secrets.DOCKER_HUB_USER }}/charity-app-backend:latest
          docker build ./frontend -t ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest
      - name: Push images to docker hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/charity-app-backend:latest
          docker push ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest

  pull-and-run:
    runs-on: ubuntu-24.04
    needs: build-and-publish
    steps:
      - name: Pull and run images on EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop charity-app-backend || true
            docker rm charity-app-backend || true
            docker pull ${{ secrets.DOCKER_HUB_USER }}/charity-app-backend:latest
            docker run -d -p 8000:8000 --name charity-app-backend ${{ secrets.DOCKER_HUB_USER }}/charity-app-backend:latest

            docker stop charity-app-frontend || true
            docker rm charity-app-frontend || true
            docker pull ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest
            docker run -d -p 8001:80 --name charity-app-frontend ${{ secrets.DOCKER_HUB_USER }}/charity-app-frontend:latest
          EOF
